version: 2

models:
  - name: names
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: stg_names
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: stg_roles
    columns:
      - name: id
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_names')
              field: role
      - name: name
        tests:
          - accepted_values:
              values: ['Applicant', 'Member']
      - name: description
        tests:
          - not_null
